import numpy as np
array1 = np.arange(10)
print(array1)
z = np.save('my_array', array1)
print(z)
x = np.load('my_array.npy')
print(x)
array2 = np.load('my_array.npy')
print(array2)
y = np.savez('multiple_arrays.npz', a1 = array1, a2 = array2)
print(y)
arrays = np.load('multiple_arrays.npz')
print(arrays['a1'])